SELECT  
    ID,
    (SELECT MATRICULE FROM `DEMANDEUR` AS D WHERE ID_DEMANDEUR = D.ID) as MATRICULE_DEM,
    IF( ISNULL(ID_BENEFICIAIRE),'Lui-même',(SELECT LIEN_PARENTE FROM `BÉNÉFICIAIRE` AS B WHERE ID_BENEFICIAIRE = B.ID)) as LIEN_PARENTE_BEN,
    STRUCTURE,ACT,STATU_DPC,
    IF(ID_AGENT1 = '1','true','false') as VALIDATION
FROM `DPC`
WHERE ID_AGENT1 = '1'
OR ISNULL(ID_AGENT1);




CREATE TABLE STRUCTURES_TIERS_PAYANT(  
    ID int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    CODE int NOT NULL,
    STRUCTURES VARCHAR(2000),
    ADRESSE VARCHAR(2000)
) DEFAULT CHARSET UTF8;
-- mysql --local-infile=1 -u root -p1

-- LOAD DATA LOCAL INFILE  
--     '/home/abdelmalek/projects/PCM-ADMIN/database/csv/structures_tiers_payant.csv'
--     INTO TABLE STRUCTURES_TIERS_PAYANT  
--     FIELDS TERMINATED BY ',' 
--     ENCLOSED BY '"'
--     LINES TERMINATED BY '\n'
--     IGNORE 1 ROWS
--     (CODE,STRUCTURES,ADRESSE);
-- END;
-- restarting id to 0
    SET  @num := 0;
    UPDATE MEDECINS_CONVENTIONNES SET id = @num := (@num+1);
    ALTER TABLE MEDECINS_CONVENTIONNES AUTO_INCREMENT =1;




